
--require("bobenemies.data")
require("bobtech.data")
require("bobplates.data")
require("bobinserters.data")
require("boblogistics.data")
require("bobmining.data")
require("bobelectronics.data")
require("bobassembly.data")
require("bobmodules.data")
require("bobpower.data")

require("angelsrefining.data")
require("angelspetrochem.data")
require("angelssmelting.data")
require("angelsbioprocessing.data")
require("angelsaddons-warehouses.data")
