
--require("bobenemies.data-updates")
require("bobtech.data-updates")
--require("bobplates.data-updates")
--require("bobinserters.data-updates")
--require("boblogistics.data-updates")
--require("bobmining.data-updates")
--require("bobelectronics.data-updates")
require("bobassembly.data-updates")

require("angelsrefining.data-updates")
require("angelspetrochem.data-updates")
require("angelssmelting.data-updates")
--require("angelsbioprocessing.data-updates")
--require("angelsaddons-warehouses.data-updates")
